---
kind: pipeline
type: docker
name: Build wasm32
trigger:
  branch:
    - master
    
steps:
- name: build
  image: rustdocker/rust
  commands:
  - apt-get install npm
  - cargo install --force cargo-node
  - cargo-node build --target browser