---
kind: pipeline
type: docker
name: Build wasm32
trigger:
  branch:
    - master
    
steps:
- name: build
  image: rustdocker/rust:stable
  commands:
  - sudo apt update -y
  - sudo apt install npm -y
  - cargo install --force cargo-node
  - cargo-node build --target browser