---
kind: pipeline
type: docker
name: Build and deplox wasm32
trigger:
  branch:
    - master
    
steps:
- name: build and deploy
  image: rust
  commands:
  - apt update -y
  - apt install npm -y
  - cargo install --force cargo-node
  - cargo-node deploy --target browser
  - git clone git@codeberg.org:flovanco/pages.git
  - cp -r target/doit-browser/ pages/doit/
  - cd pages
  - git add .
  - git commit -a -m "doit deploy"
  - git push
  environment:
    SSH_KEY:
      from_secret: drone_ssh_key
    SSH_CONFIG:
      from_secret: ssh_config

